### ISSUE TITLE
results_cenX/DXZ1

### ISSUE THREAD

**Issue by duhuipeng** [seryrzu/centroFlye#15]
But my script is running out, and I want to know where I can generated this step. Can you provide a code link for this step? I didn't see it in the scripts
![image](https://user-images.githubusercontent.com/58722433/90995890-ddd6ae80-e5ef-11ea-9106-681e24906a9f.png)

**Comment by seryrzu** [comment]
This file is generated by the centroFlye.py with the command in the README.

**Comment by duhuipeng** [comment]
Dear author, I've read this script about centroFlye.py, and I' ve running it out today, but I didn't see the output of the code that generated the DXZ1_star in this script

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/90996692-18d9e180-e5f2-11ea-9a0c-9365ca96e6ef.png)
![image](https://user-images.githubusercontent.com/58722433/90996711-27c09400-e5f2-11ea-846a-abc4043b035b.png)
 This is the script output
 I don't see the DXZ1_star  directory output

**Comment by seryrzu** [comment]
You are right. I renamed the directory to `cons_unit`. What do you need it for? If this is about jupyters - please read the README of the repo where jupyters are located

**Comment by duhuipeng** [comment]
understand the question
but  I don't understand the error in the jupyter
Since I downloaded your script and data, connected the server with jupyter, ran to find rare_centromeric_k-mers, and reported errors,I saw your mistake because you didn't download rel2_to_GRCh38.cram
However,I don't know exactly how to ask you the problem to generate this question(This is the previous screenshot)
 Because I saw the first error ;Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/ac37ec46683600f808cdd41eac1d55cd": Protocol not supported
but I'm curious what caused this

**Comment by seryrzu** [comment]
I would like to kindly repeat:

> This repository is dedicated to the main codebase of centroFlye. Not the jupyters. Please go ahead and create an issue in the [corresponding repository](https://github.com/seryrzu/centroFlye_paper_scripts).

Due to that, I close the current issue. Please **do not create** more issues in this specific repo unless there is a question about the main codebase of centroFlye and not jupyters.

**Comment by duhuipeng** [comment]
Dear author, I would like to try to assemble the centromere area of mammals (about 300 bp mono of each), Do you have any good suggestions for problems and technical difficulties? Can achieve better assembly effect? For example, parameter settings, such as survival rate, k value and so on

**Comment by duhuipeng** [comment]
Dear author, I applied your data, your setting parameters, the result of running out is 1510 units,3.1M of final_fasta,When I changed some of these parameters, like kmer=17 or 21, survival rate was 0.36 or0.38or0.40, the units and final_fasta did not change, which is why, I understand changing these parameters, their results would be somewhat different
