### ISSUE TITLE
 centromeric reads 

### ISSUE THREAD

**Issue by duhuipeng** [seryrzu/centroFlye#17]
Dear author
Using the data you provided, your software ran through the assembly of centromeres in the article,But I'm also trying to use manual assembly of centromeres,Want to Verify each other,Would you please provide a ID of these reads across centromeres,Since I used the reads ID provided in T2T article to find that it was not found in your centromere.fasta reads, only 1 out of 10 reads can be found, I guess it might be data is different version .
 I saw that T2T used 12 reads to assemble the centromere,And so I'd like to ask if you can provide reads ID, across centromeres(assembly),I want to use a manual method to verify

**Comment by seryrzu** [comment]
The read ids are available at [ZENODO](https://zenodo.org/record/3897531) in directories `centromeric_reads` for both cenX and cen6.
