### ISSUE TITLE
better_consensus_unit_reconstruction

### ISSUE THREAD

**Issue by duhuipeng** [seryrzu/centroFlye#18]
![image](https://user-images.githubusercontent.com/58722433/98444881-4e04c300-214f-11eb-9bf8-3592caa5f1d8.png)
Dear author
When I run to this step, there is an error, the error is the above picture, what is the reason, how should I do
Looking forward to your reply

**Comment by seryrzu** [comment]
Thank you for letting me know! centroFlye hasn't been tested on swine centromeres - I suspect that this is what you are trying to run it on, since the monomer is 336bp long? If so, please feel free to share the NCRF report and 336bp monomer and I will take a look.
