### ISSUE TITLE
Duplicate centromeric reads

### ISSUE THREAD

**Issue by hd00ljy** [seryrzu/centroFlye#20]
I tried cenX assembly on my sample but getting error messages on the final tandemquast step.

It seems to be due to the same reads are recruited twice.

In my sample, 4 reads were reported to be duplicated.

Is it okay if I manually remove this duplicate or does this mean something is wrong?

command1
```
grep "^>" centromeric_reads.fasta | sort | uniq -c | awk '$1>1'
```
stdout1
```
      2 >322f6dbf-c5bf-4486-8e2c-e764ea4947bf
      2 >507fbfdd-3676-4c83-bfc2-2cf2073ea27a
      2 >56d4b6ec-9491-4c3c-8d74-d727a6bb3a4c
      2 >5e4107b0-c80b-48d4-bbad-fceb11f48b3b
```

command2
```
head -n 10000 split_fasta_0.fasta | grep -n 322f6dbf-c5bf-4486-8e2c-e764ea4947bf
```

stdout2
```
2065:>322f6dbf-c5bf-4486-8e2c-e764ea4947bf runid=869182ee9e718c030eb89012b70e7246ee05373c read=38 ch=2666 start_time=2020-08-11T09:13:23Z flow_cell_id=PAF10281 protocol_group_id=20200811 sample_id=test
9088:>322f6dbf-c5bf-4486-8e2c-e764ea4947bf runid=869182ee9e718c030eb89012b70e7246ee05373c read=38 ch=2666 start_time=2020-08-11T09:13:23Z flow_cell_id=PAF10281 protocol_group_id=20200811 sample_id=test
```

**Comment by seryrzu** [comment]
Thank you for pointing that out! I think you can safely remove these reads. What is the error message of tandemQUAST?

**Comment by hd00ljy** [comment]
Oh, I actually overwrote the error log when I tried rerunning after the duplicate removal.

The error message that went out through stdout was that there are duplicate read ids.

It seems I did not clearly mention that in the original post.

**Comment by seryrzu** [comment]
Got it! Did tandemQUAST finish successfully after removing the duplicated reads?

**Comment by hd00ljy** [comment]
Yes! But sadly the process did not end well probably because the read length distribution of my sample is too short to finalize the later steps of the polishing.

**Comment by seryrzu** [comment]
Sorry to hear that. Please let me know if there is anything I can help with.

**Comment by hd00ljy** [comment]
It's kind of you to say so.
Thank you for your help again!
