### ISSUE TITLE
not an issue but a general question

### ISSUE THREAD

**Issue by jhcaddisfly** [seryrzu/centroFlye#3]
Hi,
In our project we are currently having issues with the asssembly of long repetitive regions of the genome and we would like to know if your approach (centroflye) would work on repetitive regions others then centromers.
If this is the case I would appreciate if you could explain to me how to make the reference file necessary for running centrofly.
We have long (Nanopore) reads.

Thanks,
j.

**Comment by seryrzu** [comment]
Hi,
Sorry, for the long response. Currently centroFlye only works with human centromeres. I would suggest contacting Mikhail Kolmogorov - the main developer of [Flye](https://github.com/fenderglass/Flye) assember in Pevzner's lab. Maybe Flye will work out-of-box for you.

Andrey
