### ISSUE TITLE
scripts/ext/stringdecomposer/longreads_decomposer.py is not found

### ISSUE THREAD

**Issue by 6br** [seryrzu/centroFlye#5]
Hello,
I'd like to try to run cen6 pipeline but it doesn't work because `scripts/ext/stringdecomposer/longreads_decomposer.py` is not included in `ext` folder in the current master HEAD(a1a314d). How should I handle this?
Thanks in advance.

**Comment by seryrzu** [comment]
Hello,
Thank you for your interest in centroFlye and reporting this error. String Decomposer was not included as a submodule - it is fixed now. I also slightly updated the `readme` and `run_all_cen6.sh`. Please let me know if there are any other issues.

Large updates of centroFlye are coming. Stay tuned!

**Comment by 6br** [comment]
Thank you for your quick response. I look forward to seeing the new update!
