### ISSUE TITLE
[Consulation] 

### ISSUE THREAD

**Issue by huanfa** [seryrzu/centroFlye#8]
Hi seryrzu:
   Thanks for the great job of T2T assembling. I have question about the centroFlye using in other species, such as bovine.  We do not know the HOR unit and monomor in chromosomeX, but easier to get prexfix reads and suffix reads. How could we assembly this centromere, Will the centroFlye mono mode could help to assemble the genome? Thanks a lot if you could reply.
     Best
     Huanfa

**Comment by seryrzu** [comment]
Hi, centroFlye assumes knowledge of an HOR or monomers, so, I guess, it can't be directly used for your case. However, we are working on extension of centroFlye that will not require such assumption. Stay tuned!

What is the sequencing data that you plan to use for assembly?

**Comment by huanfa** [comment]
Now we have 100x pacbio, 100x nanopore, 100x Genomics and 100x bionano data.  We have stucked in recuriting internal reads and find monomers ? Do you have any suggestions?

**Comment by seryrzu** [comment]
Is the pacbio data - clr or hifi? ONT - with ultra-long reads or without? Any estimates on the approximate length of the centromere?

We won't be able to use centroFlye for this use-case as of now but can try exchanging emails with some ideas.

**Comment by huanfa** [comment]
Thanks for the reply. I have emailed you. This one ? abzikadze@ucsd.edu
 Best
Huanfa
